### ISSUE TITLE
Debug... as written in workshop

### ISSUE THREAD

**Issue by chameleon-tbn** [kianzarrin/PedestrianBridge#2]
Hi @kianzarrin I started the game several times without having the button and without any error message. With your 'debug-Version' i got that typical error message without informations in it. But the icon is now there. (And yes, your mod works)

Please find attached the logs
[PedestrianBridge.log](https://github.com/kianzarrin/PedestrianBridge/files/4366597/PedestrianBridge.log)
[output_log.txt](https://github.com/kianzarrin/PedestrianBridge/files/4366598/output_log.txt)

additionally please check if you could move the icon a little bit.... on my 4k it stucks partially behind an other unmoveable icon

![image](https://user-images.githubusercontent.com/37211016/77266900-2c7ac800-6ca1-11ea-9f2e-6f320705cc13.png)

kind regards

**Comment by kianzarrin** [comment]
thanks for sending me this info @thebugfixnet .

> additionally please check if you could move the icon a little bit.... on my 4k it stucks partially behind an other unmoveable icon

what is that Icon by the way? There are other mods like crossings mod and roundabout builder who also put a button in there. I better get a list of all such mods so that I know where to place mine. 
![Screenshot (722)](https://user-images.githubusercontent.com/26344691/77276915-74f7ad00-6cc4-11ea-9d1f-159bd515a5e1.png)

I also need to add a shortcut key like ctrl+p. I hope that is not already occupied. I don't know how to put customizable shortcut keys yet.

>  With your 'debug-Version' i got that typical error message without information in it. 

Its the first time I hear about such a message.

as for your debug log you have stack overflow. I am surprised the game did not crash:
```
StackOverflowException: The requested operation caused a stack overflow.
  at (wrapper delegate-invoke) System.Action`1<UnityEngine.Font>:invoke_void__this___Font (UnityEngine.Font)
[line above repeated many times]
UnityEngine.Font:RequestCharactersInTexture(String, Int32, FontStyle)
ColossalFramework.UI.UIDynamicFont:RequestCharacters(String, Int32, FontStyle)
ColossalFramework.UI.DynamicFontRenderer:MeasureString(String)
EightyOne.ResourceManagers.FakeDistrictManager:UpdateNames()
DistrictManager:UpdateNamesCallback(Font)
UnityEngine.Font:InvokeTextureRebuilt_Internal(Font)
UnityEngine.Font:RequestCharactersInTexture(String, Int32, FontStyle)
ColossalFramework.UI.UIDynamicFont:FlushCharacterRequests()
ColossalFramework.UI.UIFontManager:RebuildDynamicFonts()
ColossalFramework.UI.UIView:LateUpdate()
```
your PedestrianBridge.log is much shorter than I expected Mine looks like this:
[PedestrianBridge.log](https://github.com/kianzarrin/PedestrianBridge/files/4367025/PedestrianBridge.log)

I don't see anything in the log files that suggest my Pedestrian bridge mod is causing error message . maybe its a compatibility issue. although my mod is so simple I cannot understand how could it be incompatible.

**Comment by chameleon-tbn** [comment]
The Icon is a setting of Network Extension 2. Last Tab in the settings of that mod. It enable Zone modifiing.

Ctrl+ P is already Used by several Mods. (Prop IT Up, Prop anarchy and a third one i do not remember right now.)

Maybe you can use Ctrl+B for Bridge ... I can Check Later If that one ist Not Used by the over 100 Mods i use :)

Thank you for your good Work.

**Comment by kianzarrin** [comment]
@thebugfixnet Can you please tell me what are the two grid like icons in the screenshot you sent?

**Comment by chameleon-tbn** [comment]
@kianzarrin, left one is from Zoning toolset (toggle + upgrade tool)
https://steamcommunity.com/sharedfiles/filedetails/?id=592076973

Right one is - as already described - the Road Zoning Modifier Tool from Network Extensions 2
https://steamcommunity.com/sharedfiles/filedetails/?id=812125426

**Comment by kianzarrin** [comment]
> With your 'debug-Version' i got that typical error message without informations in it.

I am unable to reproduce this. If you are still getting this error and would like it to be resolved can you please:
- Enable my mod, exit to desktop, start CS and then start a new game. Give me the log files produced. (only if you get the error if you don't then the problem obviously has been resolved.)
- Disable my mod, exit to desktop, start CS and then start a new game. Give me the new log files produced.

buy comparing the log files I can understand which error is caused due to my mod and take measures to resolve it.

**Comment by kianzarrin** [comment]
@thebugfixnet told me this is fixed and the crash was probably not this mod to begin with.
